#!/bin/sh

basename=$1

if [[ "$basename" != *. ]]; then
	basename="$1."
fi

mdfile="${basename}md"
htmlfile="${basename}html"

pandoc --mathjax --toc --from markdown+latex_macros --from markdown+pipe_tables --from markdown+raw_tex --number-sections $mdfile -s -c style.css -o $htmlfile

title=`sed "2q;d" $mdfile | cut -d'"' -f 2 | tr -d "0123456789"`
chapter=`sed '3q;d' $mdfile | cut -d'"' -f 2`
part=`sed '4q;d' $mdfile | cut -d'"' -f 2`

webdir="../content/$part/"
webfpath="${webdir}${htmlfile}"

cp $htmlfile "${webdir}${htmlfile}"

echo "---" | cat - $webfpath > tmp && mv tmp $webfpath
echo "weight: $chapter" | cat - $webfpath > tmp && mv tmp $webfpath
echo "title: '$title'" | cat - $webfpath > tmp && mv tmp $webfpath
echo "---" | cat - $webfpath > tmp && mv tmp $webfpath

